name: "Package Interface Diff"
description: "Ensure the stability of your package's API with golden testing"

inputs:
  package-name:
    description: "The package to test. Currently only one per project is supported"
    required: true
  expected-interface:
    description: "The file of the expected interface of the package. Generate it yourself with `print-api`."
    required: true
  ghc: 
    description: "The version of GHC used to compile the project. See the project's README to know which versions are supported. If the version is not supported, it will not run."
    required: true
  version:
    description: "Version of the tool"
    required: true
  public-modules:
    description: "Retain modules with the `Visibility` attribute in their Haddock documentation set to `Public`"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up the binary
      shell: bash
      run: |
        if [[ ${{ inputs.ghc }} =~ ^(9.6.6|9.8.4|9.10.1)$ ]]
        then 
          ARCHIVE=print-api-${{ inputs.version }}-Linux-static-${{ inputs.ghc }}-x86_64.tar.gz
          wget -q https://github.com/Kleidukos/print-api/releases/download/v${{ inputs.version }}/$ARCHIVE
          tar -xzvf $ARCHIVE
          chmod +x print-api
          [[ ${{ inputs.public-modules }} == "true" ]] && publicOnly="--public-only" || publicOnly=""
          ./print-api ${publicOnly} --package-name ${{ inputs.package-name }} > actual-interface.txt
          diff ${{ inputs.expected-interface }} actual-interface.txt
        else
          echo "GHC version not supported, not running."
          exit 0
        fi

branding:
  icon: 'list'
  color: 'blue'
